[package]
name = "rstw"
version = "0.1.0"
authors = ["Eiyeron"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.20"
rand = "0.8"
rand_distr = "0.4"
